### ISSUE TITLE
嗨，这个项目很好，有考虑开发vue3版本的吗

### ISSUE THREAD

**Issue by xiaoxian521** [toesbieya/el-admin-layout#1]

**Comment by toesbieya** [comment]
不考虑，因为不会ts

**Comment by xiaoxian521** [comment]
好吧，我看你改写了el-menu-item和el-submenu，是因为elementui现有的组件实现不了类似ant-design-vue的顶部导航中超出显示点点点这种样式吗？

**Comment by toesbieya** [comment]
改写的那两个只是加了`inlineIndent`，并且移除了自定义背景色，并不是为了实现类似ant-design中的水平导航菜单的响应式功能，这个是由`HeadMenu`实现的
