### ISSUE TITLE
自动隐藏开启后面包屑和菜单搜索都没有了 

### ISSUE THREAD

**Issue by ChenHaoYang0** [toesbieya/el-admin-layout#4]
![Snipaste_2023-11-28_16-51-34](https://github.com/toesbieya/el-admin-layout/assets/30863918/507d0233-ac7e-41a2-90de-9c2841b931e6)
有办法解决吗？

**Comment by toesbieya** [comment]
怎么写的，来个代码

**Comment by ChenHaoYang0** [comment]
就是引入你的复杂功能里面的代码， 基本没有修改。  你目前的在线演示点击自动隐藏 也是一样的。

**Comment by toesbieya** [comment]
复杂功能，这个并没有写菜单搜索吧，面包屑试了开自动隐藏没啥问题，

**Comment by ChenHaoYang0** [comment]
![Snipaste_2023-12-15_14-17-56](https://github.com/toesbieya/el-admin-layout/assets/30863918/63bc3913-9a44-4cdc-b65e-c8e2c0633414)
![Snipaste_2023-12-15_14-18-12](https://github.com/toesbieya/el-admin-layout/assets/30863918/d38d05c6-32b2-4c38-bdd5-a7878c1d3ccf)
https://toesbieya.cn/el-admin-layout/#/index 
 我在这个网站测试自动隐藏  汉堡包就会消失呢

**Comment by toesbieya** [comment]
。。我以为是说的面包屑
设置了侧边栏自动隐藏的话，侧边栏底部默认不会渲染汉堡包
