### ISSUE TITLE
请问引入Screenfull后，点击全屏按钮 能否做到全屏page-content 部分，怎么获取page-content呢

### ISSUE THREAD

**Issue by ChenHaoYang0** [toesbieya/el-admin-layout#5]
![image](https://github.com/toesbieya/el-admin-layout/assets/30863918/9a5a83e2-eb0a-445a-8e93-b18bd82c45ea)

**Comment by toesbieya** [comment]
目前直接根据类名拿，直接dom.requestFullscreen()
