### ISSUE TITLE
从服务器加载菜单怎么激活二级菜单

### ISSUE THREAD

**Issue by ChenHaoYang0** [toesbieya/el-admin-layout#6]
![Snipaste_2023-12-15_17-45-04](https://github.com/toesbieya/el-admin-layout/assets/30863918/ffd0b25b-5ff5-47b5-b826-31e1ba089dde)
F12报这个错误，然后左边菜单未激活，我是后端开发 这块有点没弄清楚
对应的index前端代码如下

[index.txt](https://github.com/toesbieya/el-admin-layout/files/13683794/index.txt)

**Comment by toesbieya** [comment]
警告是因为logo没渲染，导致传给aside-header的default是false，和props中定义的Object类型不符，不过不影响使用
菜单没高亮应该是没有能和当前地址匹配的菜单，完整的菜单数据发出来看看

**Comment by ChenHaoYang0** [comment]
menu 目录 index.js 如下
export default [
	{
		fullPath: '/',
		meta: { title: '根菜单' },
		children: [
			{
				fullPath: '/index',
				meta: { title: '首页' },
				children: [],
			},
			{
				fullPath: '/test',
				meta: { title: '测试页' },
				children: [],
			},
			{
				fullPath: '/reuse/1',
				meta: { title: '复用路由1' },
				children: [],
			},
			{
				fullPath: '/reuse/2',
				meta: { title: '复用路由2' },
				children: [],
			},
		],
	},
]

router.js  如下
import Layout from '../views'
import IndexPage from '@/layout/common/view/indexPage.vue'
import TestPage from '@/layout/common/view/testPage.vue'
import ReusablePage from '@/layout/common/view/reusablePage.vue'
import Nest0 from '@/layout/common/view/nest0.vue'
import Nest0_1 from '@/layout/common/view/nest0-1.vue'
import SimpleBreadcrumbPage from '@/layout/common/view/breadcrumb/simple.vue'
import ListBreadcrumbPage from '@/layout/common/view/breadcrumb/list.vue'
import DetailBreadcrumbPage from '@/layout/common/view/breadcrumb/detail.vue'

const _import = require('@/utils/util/import-' + process.env.NODE_ENV)

export default [
	{
		path: '/',
		redirect: 'index',
		component: Layout,
		children: [
			// 首页
			{
				path: 'index',
				name: 'indexPage',
				component: IndexPage,
				meta: { title: '首页' },
			},
			{
				path: '404',
				name: '404',
				component: _import('404'),
			},
			{
				path: 'test',
				name: 'testPage',
				component: TestPage,
				meta: { title: '测试页', noCache: true },
			},
			{
				path: 'reuse/:id',
				props: true,
				component: ReusablePage,
				meta: { dynamicTitle: (route) => `复用路由${route.params.id}`, usePathKey: true },
			},
			{
				path: 'nest0',
				component: Nest0,
				meta: { title: '嵌套页0' },
			},
			{
				path: 'nest0-1',
				component: Nest0_1,
				meta: { title: '嵌套页0-1' },
			},
		],
	},
	{
		path: '/iframe',
		component: Layout,
		children: [
			{
				path: 'taobao',
				name: 'taobao',
				meta: { title: '淘宝', dynamicTitle: () => `淘宝${Date.now()}`, iframe: 'https://www.taobao.com' },
			},
			{
				path: 'baidu',
				name: 'baidu',
				meta: { title: '百度', iframe: 'https://www.baidu.com' },
			},
		],
	},
	{
		path: '/breadcrumb',
		component: Layout,
		children: [
			{
				path: 'simple',
				component: SimpleBreadcrumbPage,
				meta: { title: '简单' },
			},
			{
				path: 'list',
				component: ListBreadcrumbPage,
				meta: { title: '列表页' },
			},
			{
				path: 'detail/:id',
				props: true,
				component: DetailBreadcrumbPage,
				meta: { dynamicTitle: (route) => `详情页${route.params.id}`, activeMenu: '/breadcrumb/list' },
			},
		],
	},
]


这个也没默认选中2级菜单

**Comment by ChenHaoYang0** [comment]
// appMutations.loadingMenu(true)
// asideMutations.alwaysRender(true)
这个2个注释掉，就没有警告了 但是左边菜单也出不来了，有办法解决吗？

**Comment by toesbieya** [comment]
来个最小复现仓库吧，我试了可以正常高亮

**Comment by ChenHaoYang0** [comment]
加了一个activeMenu: '/index'     2级菜单可以高亮显示了meta: { title: '首页', activeMenu: '/index' },
现在只有 
[Vue warn]: Invalid prop: type check failed for prop "default". Expected Object, got Boolean with value false.

found in

---> <Layout> at src/views/index.vue
       <App> at src/app.vue
         <Root>
         这个错误 
           
         	<template v-slot:aside-header="defaultContent">
				<aside-header :default="defaultContent" />
			</template>
			这个又必须要用

**Comment by toesbieya** [comment]
警告可以不用管，或者你把`aside-header`组件里的`props.default.type`改成`null`

**Comment by ChenHaoYang0** [comment]
好的 感谢
