### ISSUE TITLE
请问设置redirectPath: '/'后 点击刷新按钮白屏如何解决

### ISSUE THREAD

**Issue by ChenHaoYang0** [toesbieya/el-admin-layout#7]
![image](https://github.com/toesbieya/el-admin-layout/assets/30863918/5dbc07ea-ae3a-4983-94e0-e60c40562177)
![image](https://github.com/toesbieya/el-admin-layout/assets/30863918/ab35d8b1-5560-42d8-a413-2e080b91671b)

**Comment by ChenHaoYang0** [comment]
http://localhost:8080/index 地址还是这个 屏幕白屏  再次点击重复菜单也是一样

**Comment by toesbieya** [comment]
redirectPath不能设为'/'

**Comment by ChenHaoYang0** [comment]
redirectPath: '/redirect', 修改成这个后  页面地址变成 http://localhost:8080/redirect/index  ，然后白屏 

xport default [
	{
		path: '/',
		redirect: 'index',
		component: Layout,
		children: [
			// 首页
			{
				path: 'index',
				name: 'index',
				component: IndexPage,
				meta: { title: '首页', activeMenu: '/index' },
			},
			{
				path: '404',
				name: '404',
				component: _import('404'),
			},
		],
	},
	// 大屏菜单
	{
		path: '/menu/index',
		name: 'menu',
		component: _import('iotmoniter/menu/index'),
	},
	// 大屏
	{
		path: '/monitor/index',
		name: 'monitor',
		component: _import('iotmoniter/monitor/index'),
	},
	// 大屏 编辑
	{
		path: '/monitor/edit',
		name: 'monitor-edit',
		component: _import('iotmoniter/monitor/edit'),
	},
	// 大屏 详情
	{
		path: '/monitor/detail',
		name: 'monitor-detail',
		component: _import('iotmoniter/monitor/detail'),
	},
]

routers.js只能用这种方式 ，用export default createRouter(Layout)这种的要报错

**Comment by toesbieya** [comment]
![Snipaste_2024-01-12_16-56-44](https://github.com/toesbieya/el-admin-layout/assets/45418945/71b11cac-03ab-4fa5-b28e-c0134840eb83)
